imports:
  - { resource: index/* }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # auto-register all commands as services
  Neusta\ElasticIndexBundle\Command\:
    resource: '../src/Command/*'
    tags: [ 'console.command' ]

  JoliCode\Elastically\Client:
    arguments:
      $config:
        elastically_index_class_mapping: []
